# -*- coding: utf-8 -*-
from odoo import models, fields

class SaleOrder(models.Model):
    _inherit = 'sale.order'

    # You can rename these to whatever you like
    x_metric_01 = fields.Float(string="Metric 01")
    x_metric_02 = fields.Float(string="Metric 02")
    x_metric_03 = fields.Float(string="Metric 03")
    x_metric_04 = fields.Float(string="Metric 04")
    x_metric_05 = fields.Float(string="Metric 05")
    x_metric_06 = fields.Float(string="Metric 06")
    x_metric_07 = fields.Float(string="Metric 07")
    x_metric_08 = fields.Float(string="Metric 08")
    x_metric_09 = fields.Float(string="Metric 09")
    x_metric_10 = fields.Float(string="Metric 10")
    x_metric_11 = fields.Float(string="Metric 11")
    x_metric_12 = fields.Float(string="Metric 12")
    x_metric_13 = fields.Float(string="Metric 13")
    x_metric_14 = fields.Float(string="Metric 14")
    x_metric_15 = fields.Float(string="Metric 15")
    x_metric_16 = fields.Float(string="Metric 16")
    x_metric_17 = fields.Float(string="Metric 17")
    x_metric_18 = fields.Float(string="Metric 18")
    x_metric_19 = fields.Float(string="Metric 19")
    x_metric_20 = fields.Float(string="Metric 20")
    x_metric_21 = fields.Float(string="Metric 20")
    x_metric_22 = fields.Float(string="Metric 20")
    x_metric_23 = fields.Float(string="Metric 20")
    x_metric_24 = fields.Float(string="Metric 20")
    x_metric_25 = fields.Float(string="Metric 20")
    x_metric_26 = fields.Float(string="Metric 20")
    x_metric_27 = fields.Float(string="Metric 20")
    x_metric_28 = fields.Float(string="Metric 20")
    x_metric_29 = fields.Float(string="Metric 20")
    x_metric_30 = fields.Float(string="Metric 20")
    x_metric_31 = fields.Float(string="Metric 20")
    x_metric_32 = fields.Float(string="Metric 20")
    x_metric_33 = fields.Float(string="Metric 20")
    x_metric_34 = fields.Float(string="Metric 20")
    x_metric_35 = fields.Float(string="Metric 20")
    x_metric_36 = fields.Float(string="Metric 20")
    x_metric_37 = fields.Float(string="Metric 20")
    x_metric_38 = fields.Float(string="Metric 20")
    x_metric_39 = fields.Float(string="Metric 20")
    x_metric_40 = fields.Float(string="Metric 20")
    x_metric_41 = fields.Float(string="Metric 20")
    x_metric_42 = fields.Float(string="Metric 20")
    x_metric_43 = fields.Float(string="Metric 20")
    x_metric_44 = fields.Float(string="Metric 20")
    x_metric_45 = fields.Float(string="Metric 20")
    x_metric_46 = fields.Float(string="Metric 20")
    x_metric_47 = fields.Float(string="Metric 20")
    x_metric_48 = fields.Float(string="Metric 20")
    x_metric_49 = fields.Float(string="Metric 20")

