# -*- coding: utf-8 -*-
# Copyright (c) Open Value All Rights Reserved

{
    "name": "MRP Master Production Plan",
    "summary": 'Master Production Plan',
    "version": "14.0.1.4",
    "category": "Manufacturing",
    "website": 'www.openvalue.cloud',
    "author": "OpenValue",
    "support": 'info@openvalue.cloud',
    "license": "Other proprietary",
    "price": 1500.00,
    "currency": 'EUR',

    "depends": [
        "mrp_subcontracting",
        "mrp_shop_floor_control",
        "purchase_stock",
        "openvalue_warehouse_calendar",
        "sale_management",
        "stock_transfer_interwarehouses",
    ],
    "data": [
        "security/mrp_master_production_plan_security.xml",
        "security/ir.model.access.csv",
        "data/mrp_master_production_plan_sequence.xml",
        "views/res_config_settings_views.xml",
        "views/mrp_mpp_parameters_views.xml",
        "views/product_views.xml",
        "views/mrp_planning_version_views.xml",
        "wizards_pir/mrp_pir_massive_create.xml",
        "views/mrp_independent_requirements_views.xml",
        "wizards_dpi/mrp_dpi_po_creation.xml",
        "wizards_ddi/mrp_ddi_st_creation.xml",
        "views/mrp_distribution_deployment_views.xml",
        "views/mrp_distribution_procurement_views.xml",
        "wizards_sop/mrp_sop_massive_planning.xml",
        "views/mrp_sales_operations_plan_views.xml",
        "views/mrp_sop_capacity_views.xml",
        "wizards_mpp/mrp_mpp_po_creation.xml",
        "views/mrp_production_plan_views.xml",
        "views/mrp_mpp_capacity_views.xml",
        "views/mrp_mpp_menu.xml",
    ],
    "application": False,
    "installable": True,
    "auto_install": False,
    "images": ['static/description/banner.png'],
}
